[package]
name = "sim-rust"
version = "0.1.0"
edition = "2021"
authors = ["Gavin Heinrichs-Majetich <gmh33@pitt.edu>"]
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
